name: Check for Cheaper flight!!
#Make sure to use UTC time for this schedule https://savvytime.com/converter/cst-to-utc
#Order is minute hour(use military time) day of month(1-31) month (1-12) day of week (0-6 SUN-SAT)
on:
  schedule:
    - cron: '27 19 * * *'
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 19
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test tests/flight-check.spec.ts --project=firefox
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
